config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :photoworkouts

      resources :privileges

      resources :teams

      resources :participations

      resources :challenges

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "challenges#index"
  resources :photoworkouts
  resources :privileges
  resources :teams
  resources :participations
  resources :challenges
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/participation.rb
class Participation < ApplicationRecord
  # Direct associations

  belongs_to :team

  belongs_to :challenge

  belongs_to :user

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    user.to_s
  end
end

app/controllers/api/v1/participations_controller.rb
class Api::V1::ParticipationsController < Api::V1::GraphitiController
  def index
    participations = ParticipationResource.all(params)
    respond_with(participations)
  end

  def show
    participation = ParticipationResource.find(params)
    respond_with(participation)
  end

  def create
    participation = ParticipationResource.build(params)

    if participation.save
      render jsonapi: participation, status: :created
    else
      render jsonapi_errors: participation
    end
  end

  def update
    participation = ParticipationResource.find(params)

    if participation.update_attributes
      render jsonapi: participation
    else
      render jsonapi_errors: participation
    end
  end

  def destroy
    participation = ParticipationResource.find(params)

    if participation.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: participation
    end
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :set_participation, only: %i[show edit update destroy]

  def index
    @q = Participation.ransack(params[:q])
    @participations = @q.result(distinct: true).includes(:user, :challenge,
                                                         :team).page(params[:page]).per(10)
  end

  def show; end

  def new
    @participation = Participation.new
  end

  def edit; end

  def create
    @participation = Participation.new(participation_params)

    if @participation.save
      message = "Participation was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @participation, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @participation.update(participation_params)
      redirect_to @participation,
                  notice: "Participation was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @participation.destroy
    message = "Participation was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to participations_url, notice: message
    end
  end

  private

  def set_participation
    @participation = Participation.find(params[:id])
  end

  def participation_params
    params.require(:participation).permit(:user_id, :challenge_id, :team_id)
  end
end

app/views/participations/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Participation #<%= participation.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>User</dt>
      <dd>
        <% if @participation.user.present? %>
          <%= link_to participation.user, participation.user %>
        <% end %>
      </dd>

      <dt>Challenge</dt>
      <dd>
        <% if @participation.challenge.present? %>
          <%= link_to participation.challenge, participation.challenge %>
        <% end %>
      </dd>

      <dt>Team</dt>
      <dd>
        <% if @participation.team.present? %>
          <%= link_to participation.team, participation.team %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back participation, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_participation_url(participation), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to participation, method: :delete, data: { confirm: "Do you really want to delete this participation?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(participation.updated_at) %> ago
  </div>
</div>

app/views/participations/_form.html.erb
<% was_validated = participation.errors.any? %>

<%= form_with(model: participation, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% user_class = "form-control" %>
    <% user_was_invalid = participation.errors.include?(:user) %>

    <% if was_validated %>
      <% if user_was_invalid %>
        <% user_class << " is-invalid" %>
      <% else %>
        <% user_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if user_was_invalid %>
      <% participation.errors.full_messages_for(:user).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% challenge_class = "form-control" %>
    <% challenge_was_invalid = participation.errors.include?(:challenge) %>

    <% if was_validated %>
      <% if challenge_was_invalid %>
        <% challenge_class << " is-invalid" %>
      <% else %>
        <% challenge_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :challenge_id %>
    <%= f.collection_select :challenge_id, Challenge.all, :id, :to_s, {}, class: "form-control" %>
    <% if challenge_was_invalid %>
      <% participation.errors.full_messages_for(:challenge).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% team_class = "form-control" %>
    <% team_was_invalid = participation.errors.include?(:team) %>

    <% if was_validated %>
      <% if team_was_invalid %>
        <% team_class << " is-invalid" %>
      <% else %>
        <% team_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :team_id %>
    <%= f.collection_select :team_id, Team.all, :id, :to_s, {}, class: "form-control" %>
    <% if team_was_invalid %>
      <% participation.errors.full_messages_for(:team).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/participations/_list_item.html.erb
<%= link_to participation, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= participation %>
    <small class="text-muted">
      <%= time_ago_in_words(participation.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/participations/_participations_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "participations_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :user_email_cont, "User email contains" %>
    <%= f.text_field :user_email_cont, :class => "form-control", :placeholder => "User email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :starting_time, "Challenge Starting time" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='challengegteqstarting_timePicker' data-target-input="nearest">
          <%= f.text_field :challenge_starting_time_gteq, :class => "form-control datetimepicker-input", :placeholder => "Challenge Starting time greater than or equal to", :data => {:target => '#challengegteqstarting_timePicker'} %>
          <div class="input-group-append" data-target='#challengegteqstarting_timePicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='challengelteqstarting_timePicker' data-target-input="nearest">
          <%= f.text_field :challenge_starting_time_lteq, :class => "form-control datetimepicker-input", :placeholder => "Challenge Starting time less than or equal to", :data => {:target => '#challengelteqstarting_timePicker'} %>
          <div class="input-group-append" data-target='#challengelteqstarting_timePicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#challengegteqstarting_timePicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#challengelteqstarting_timePicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#challengegteqstarting_timePicker').on("dp.change", function (e) {
              $('#challengelteqstarting_timePicker').data("DateTimePicker").minDate(e.date);
          });
          $('#challengelteqstarting_timePicker').on("dp.change", function (e) {
              $('#challengegteqstarting_timePicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :team_team_name_cont, "Team team_name contains" %>
    <%= f.text_field :team_team_name_cont, :class => "form-control", :placeholder => "Team team_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/participations" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#participations_filters">
  Show filters
</a>

app/views/participations/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Participation #<%= @participation.id %>
      </h2>

      <div class="card-body">
        <%= render "form", participation: @participation %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/participations/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Participations

      <%= link_to new_participation_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "participations/participations_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Participations

        <%= link_to new_participation_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @participations, partial: "list_item", as: :participation %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @participations, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/participations/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Participation
      </h2>

      <div class="card-body">
        <%= render "form", participation: @participation %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/participations/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @participation, partial: "card", as: :participation %>
  </div>
</div>