config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :photoworkouts

      resources :privileges

      resources :teams

      resources :participations

      resources :challenges

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "challenges#index"
  resources :photoworkouts
  resources :privileges
  resources :teams
  resources :participations
  resources :challenges
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/photoworkout.rb
class Photoworkout < ApplicationRecord
  mount_uploader :photo_locator, PhotoLocatorUploader

  # Direct associations

  belongs_to :challenge

  belongs_to :user

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    caption
  end
end

app/controllers/api/v1/photoworkouts_controller.rb
class Api::V1::PhotoworkoutsController < Api::V1::GraphitiController
  def index
    photoworkouts = PhotoworkoutResource.all(params)
    respond_with(photoworkouts)
  end

  def show
    photoworkout = PhotoworkoutResource.find(params)
    respond_with(photoworkout)
  end

  def create
    photoworkout = PhotoworkoutResource.build(params)

    if photoworkout.save
      render jsonapi: photoworkout, status: :created
    else
      render jsonapi_errors: photoworkout
    end
  end

  def update
    photoworkout = PhotoworkoutResource.find(params)

    if photoworkout.update_attributes
      render jsonapi: photoworkout
    else
      render jsonapi_errors: photoworkout
    end
  end

  def destroy
    photoworkout = PhotoworkoutResource.find(params)

    if photoworkout.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: photoworkout
    end
  end
end

app/controllers/photoworkouts_controller.rb
class PhotoworkoutsController < ApplicationController
  before_action :set_photoworkout, only: %i[show edit update destroy]

  def index
    @q = Photoworkout.ransack(params[:q])
    @photoworkouts = @q.result(distinct: true).includes(:user,
                                                        :challenge).page(params[:page]).per(10)
  end

  def show; end

  def new
    @photoworkout = Photoworkout.new
  end

  def edit; end

  def create
    @photoworkout = Photoworkout.new(photoworkout_params)

    if @photoworkout.save
      message = "Photoworkout was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @photoworkout, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @photoworkout.update(photoworkout_params)
      redirect_to @photoworkout,
                  notice: "Photoworkout was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @photoworkout.destroy
    message = "Photoworkout was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to photoworkouts_url, notice: message
    end
  end

  private

  def set_photoworkout
    @photoworkout = Photoworkout.find(params[:id])
  end

  def photoworkout_params
    params.require(:photoworkout).permit(:caption, :challenge_id, :user_id,
                                         :likes_count, :photo_locator, :calories, :main_exercise)
  end
end

app/views/photoworkouts/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Photoworkout #<%= photoworkout.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Caption</dt>
      <dd><%= photoworkout.caption %></dd>

      <dt>Challenge</dt>
      <dd>
        <% if @photoworkout.challenge.present? %>
          <%= link_to photoworkout.challenge, photoworkout.challenge %>
        <% end %>
      </dd>

      <dt>User</dt>
      <dd>
        <% if @photoworkout.user.present? %>
          <%= link_to photoworkout.user, photoworkout.user %>
        <% end %>
      </dd>

      <dt>Likes count</dt>
      <dd><%= photoworkout.likes_count %></dd>

      <dt>Photo locator</dt>
      <dd>
        <%= cl_image_tag @photoworkout.photo_locator, class: "img-fluid" %>
      </dd>

      <dt>Calories</dt>
      <dd><%= photoworkout.calories %></dd>

      <dt>Main exercise</dt>
      <dd><%= photoworkout.main_exercise %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back photoworkout, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_photoworkout_url(photoworkout), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to photoworkout, method: :delete, data: { confirm: "Do you really want to delete this photoworkout?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(photoworkout.updated_at) %> ago
  </div>
</div>

app/views/photoworkouts/_form.html.erb
<% was_validated = photoworkout.errors.any? %>

<%= form_with(model: photoworkout, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% caption_class = "form-control" %>
    <% caption_was_invalid = photoworkout.errors.include?(:caption) %>

    <% if was_validated %>
      <% if caption_was_invalid %>
        <% caption_class << " is-invalid" %>
      <% else %>
        <% caption_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :caption %>
    <%= f.text_area :caption, class: caption_class, placeholder: "Enter caption" %>
    <% if caption_was_invalid %>
      <% photoworkout.errors.full_messages_for(:caption).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% challenge_class = "form-control" %>
    <% challenge_was_invalid = photoworkout.errors.include?(:challenge) %>

    <% if was_validated %>
      <% if challenge_was_invalid %>
        <% challenge_class << " is-invalid" %>
      <% else %>
        <% challenge_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :challenge_id %>
    <%= f.collection_select :challenge_id, Challenge.all, :id, :to_s, {}, class: "form-control" %>
    <% if challenge_was_invalid %>
      <% photoworkout.errors.full_messages_for(:challenge).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% user_class = "form-control" %>
    <% user_was_invalid = photoworkout.errors.include?(:user) %>

    <% if was_validated %>
      <% if user_was_invalid %>
        <% user_class << " is-invalid" %>
      <% else %>
        <% user_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if user_was_invalid %>
      <% photoworkout.errors.full_messages_for(:user).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% likes_count_class = "form-control" %>
    <% likes_count_was_invalid = photoworkout.errors.include?(:likes_count) %>

    <% if was_validated %>
      <% if likes_count_was_invalid %>
        <% likes_count_class << " is-invalid" %>
      <% else %>
        <% likes_count_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :likes_count %>
    <%= f.number_field :likes_count, class: likes_count_class, placeholder: "Enter likes count" %>
    <% if likes_count_was_invalid %>
      <% photoworkout.errors.full_messages_for(:likes_count).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% photo_locator_class = "form-control" %>
    <% photo_locator_was_invalid = photoworkout.errors.include?(:photo_locator) %>

    <% if was_validated %>
      <% if photo_locator_was_invalid %>
        <% photo_locator_class << " is-invalid" %>
      <% else %>
        <% photo_locator_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :photo_locator %>
    <%= f.file_field :photo_locator, class: "form-control" %>
    <% if photo_locator_was_invalid %>
      <% photoworkout.errors.full_messages_for(:photo_locator).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% calory_class = "form-control" %>
    <% calory_was_invalid = photoworkout.errors.include?(:calory) %>

    <% if was_validated %>
      <% if calory_was_invalid %>
        <% calory_class << " is-invalid" %>
      <% else %>
        <% calory_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :calories %>
    <%= f.number_field :calories, class: calory_class, placeholder: "Enter calory" %>
    <% if calory_was_invalid %>
      <% photoworkout.errors.full_messages_for(:calory).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% main_exercise_class = "form-control" %>
    <% main_exercise_was_invalid = photoworkout.errors.include?(:main_exercise) %>

    <% if was_validated %>
      <% if main_exercise_was_invalid %>
        <% main_exercise_class << " is-invalid" %>
      <% else %>
        <% main_exercise_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :main_exercise %>
    <%= f.text_field :main_exercise, class: main_exercise_class, placeholder: "Enter main exercise" %>
    <% if main_exercise_was_invalid %>
      <% photoworkout.errors.full_messages_for(:main_exercise).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/photoworkouts/_list_item.html.erb
<%= link_to photoworkout, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= photoworkout %>
    <small class="text-muted">
      <%= time_ago_in_words(photoworkout.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/photoworkouts/_photoworkouts_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "photoworkouts_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :caption_cont, "Caption contains" %>
    <%= f.text_field :caption_cont, :class => "form-control", :placeholder => "Caption contains" %>
  </div>

  <div class="form-group">
    <%= f.label :main_exercise_cont, "Main exercise contains" %>
    <%= f.text_field :main_exercise_cont, :class => "form-control", :placeholder => "Main exercise contains" %>
  </div>

  <div class="form-group">
    <%= f.label :calories, "Calories" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :calories_gteq, :class => "form-control", :placeholder => "Calories greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :calories_lteq, :class => "form-control", :placeholder => "Calories less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :likes_count, "Likes count" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :likes_count_gteq, :class => "form-control", :placeholder => "Likes count greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :likes_count_lteq, :class => "form-control", :placeholder => "Likes count less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :user_email_cont, "User email contains" %>
    <%= f.text_field :user_email_cont, :class => "form-control", :placeholder => "User email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :starting_time, "Challenge Starting time" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='challengegteqstarting_timePicker' data-target-input="nearest">
          <%= f.text_field :challenge_starting_time_gteq, :class => "form-control datetimepicker-input", :placeholder => "Challenge Starting time greater than or equal to", :data => {:target => '#challengegteqstarting_timePicker'} %>
          <div class="input-group-append" data-target='#challengegteqstarting_timePicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='challengelteqstarting_timePicker' data-target-input="nearest">
          <%= f.text_field :challenge_starting_time_lteq, :class => "form-control datetimepicker-input", :placeholder => "Challenge Starting time less than or equal to", :data => {:target => '#challengelteqstarting_timePicker'} %>
          <div class="input-group-append" data-target='#challengelteqstarting_timePicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#challengegteqstarting_timePicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#challengelteqstarting_timePicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#challengegteqstarting_timePicker').on("dp.change", function (e) {
              $('#challengelteqstarting_timePicker').data("DateTimePicker").minDate(e.date);
          });
          $('#challengelteqstarting_timePicker').on("dp.change", function (e) {
              $('#challengegteqstarting_timePicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/photoworkouts" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#photoworkouts_filters">
  Show filters
</a>

app/views/photoworkouts/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Photoworkout #<%= @photoworkout.id %>
      </h2>

      <div class="card-body">
        <%= render "form", photoworkout: @photoworkout %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/photoworkouts/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Photoworkouts

      <%= link_to new_photoworkout_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "photoworkouts/photoworkouts_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Photoworkouts

        <%= link_to new_photoworkout_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @photoworkouts, partial: "list_item", as: :photoworkout %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @photoworkouts, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/photoworkouts/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Photoworkout
      </h2>

      <div class="card-body">
        <%= render "form", photoworkout: @photoworkout %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/photoworkouts/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @photoworkout, partial: "card", as: :photoworkout %>
  </div>
</div>