config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :photoworkouts

      resources :privileges

      resources :teams

      resources :participations

      resources :challenges

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "challenges#index"
  resources :photoworkouts
  resources :privileges
  resources :teams
  resources :participations
  resources :challenges
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_picture, ProfilePictureUploader

  include JwtToken
  # Direct associations

  has_many   :photos,
             class_name: "Photoworkout",
             dependent: :destroy

  has_many   :participations,
             dependent: :destroy

  has_many   :privileges,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    email
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::GraphitiController
  def index
    users = UserResource.all(params)
    respond_with(users)
  end

  def show
    user = UserResource.find(params)
    respond_with(user)
  end

  def create
    user = UserResource.build(params)

    if user.save
      render jsonapi: user, status: :created
    else
      render jsonapi_errors: user
    end
  end

  def update
    user = UserResource.find(params)

    if user.update_attributes
      render jsonapi: user
    else
      render jsonapi_errors: user
    end
  end

  def destroy
    user = UserResource.find(params)

    if user.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @photoworkout = Photoworkout.new
    @participation = Participation.new
    @privilege = Privilege.new
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:is_premium, :profile_picture, :bio,
                                 :username)
  end
end

app/views/users/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    User #<%= user.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Is premium</dt>
      <dd><%= user.is_premium %></dd>

      <dt>Profile picture</dt>
      <dd>
        <%= cl_image_tag @user.profile_picture, class: "img-fluid" %>
      </dd>

      <dt>Bio</dt>
      <dd><%= user.bio %></dd>

      <dt>Username</dt>
      <dd><%= user.username %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back user, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_user_url(user), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to user, method: :delete, data: { confirm: "Do you really want to delete this user?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(user.updated_at) %> ago
  </div>
</div>

app/views/users/_form.html.erb
<% was_validated = user.errors.any? %>

<%= form_with(model: user, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-check">
    <% is_premium_class = "form-check-input" %>
    <% is_premium_was_invalid = user.errors.include?(:is_premium) %>

    <% if was_validated %>
      <% if is_premium_was_invalid %>
        <% is_premium_class << " is-invalid" %>
      <% else %>
        <% is_premium_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :is_premium, class: "form-check-label" do %>
      <%= f.check_box :is_premium, class: is_premium_class %> Is premium
    <% end %>
    <% if is_premium_was_invalid %>
      <% user.errors.full_messages_for(:is_premium).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% profile_picture_class = "form-control" %>
    <% profile_picture_was_invalid = user.errors.include?(:profile_picture) %>

    <% if was_validated %>
      <% if profile_picture_was_invalid %>
        <% profile_picture_class << " is-invalid" %>
      <% else %>
        <% profile_picture_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :profile_picture %>
    <%= f.text_field :profile_picture, class: profile_picture_class, placeholder: "Enter profile picture" %>
    <% if profile_picture_was_invalid %>
      <% user.errors.full_messages_for(:profile_picture).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% bio_class = "form-control" %>
    <% bio_was_invalid = user.errors.include?(:bio) %>

    <% if was_validated %>
      <% if bio_was_invalid %>
        <% bio_class << " is-invalid" %>
      <% else %>
        <% bio_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :bio %>
    <%= f.text_area :bio, class: bio_class, placeholder: "Enter bio" %>
    <% if bio_was_invalid %>
      <% user.errors.full_messages_for(:bio).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% username_class = "form-control" %>
    <% username_was_invalid = user.errors.include?(:username) %>

    <% if was_validated %>
      <% if username_was_invalid %>
        <% username_class << " is-invalid" %>
      <% else %>
        <% username_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :username %>
    <%= f.text_field :username, class: username_class, placeholder: "Enter username" %>
    <% if username_was_invalid %>
      <% user.errors.full_messages_for(:username).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/users/_list_item.html.erb
<%= link_to user, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= user %>
    <small class="text-muted">
      <%= time_ago_in_words(user.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/users/_user_participations.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Participations

    <a data-toggle="collapse" href="#user_participations_new_form">
      Add participation
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.participations.each do |participation| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to participation, participation %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_participations_new_form">
        <%= render partial: "users/user_participations_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_participations_new_form.html.erb
<%= form_with(model: @participation, local: true) do |f| %>

  <%= f.hidden_field :user_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :challenge_id %>

    <%= f.collection_select :challenge_id, Challenge.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :team_id %>

    <%= f.collection_select :team_id, Team.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create participation", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/_user_photos.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Photos

    <a data-toggle="collapse" href="#user_photos_new_form">
      Add photoworkout
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.photos.each do |photoworkout| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to photoworkout, photoworkout %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_photos_new_form">
        <%= render partial: "users/user_photos_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_photos_new_form.html.erb
<%= form_with(model: @photoworkout, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :caption %>
    <%= f.text_area :caption, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :challenge_id %>

    <%= f.collection_select :challenge_id, Challenge.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :user_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :likes_count %>

    <%= f.text_field :likes_count, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :photo_locator %>

    <%= f.file_field :photo_locator, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :calories %>

    <%= f.text_field :calories, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :main_exercise %>

    <%= f.text_field :main_exercise, class: "form-control" %>
  </div>

  <%= f.submit "Create photoworkout", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/_user_privileges.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Privileges

    <a data-toggle="collapse" href="#user_privileges_new_form">
      Add privilege
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.privileges.each do |privilege| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to privilege, privilege %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_privileges_new_form">
        <%= render partial: "users/user_privileges_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_privileges_new_form.html.erb
<%= form_with(model: @privilege, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :challenge_id %>

    <%= f.collection_select :challenge_id, Challenge.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :user_id, value: @user.id %>

  <%= f.submit "Create privilege", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit User #<%= @user.id %>
      </h2>

      <div class="card-body">
        <%= render "form", user: @user %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Users

      <%= link_to new_user_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>






<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Users

        <%= link_to new_user_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @users, partial: "list_item", as: :user %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @users, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New User
      </h2>

      <div class="card-body">
        <%= render "form", user: @user %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @user, partial: "card", as: :user %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_privileges" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_participations" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_photos" %>
  </div>
</div>